# Generated by Django 4.2 on 2024-03-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
