# Generated by Django 4.2 on 2024-03-17 19:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0003_project_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300000),
        ),
    ]
