# Generated by Django 4.2 on 2024-03-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0004_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auther',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
