# Generated by Django 4.2 on 2024-03-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0005_project_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='auther',
            new_name='collaborators',
        ),
    ]
