# Generated by Django 4.2 on 2024-03-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0008_glance'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dob', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/footer_profile')),
                ('video_link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Cerficate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/certificates')),
                ('news', models.TextField()),
                ('bugFix', models.TextField()),
            ],
        ),
    ]
