# Generated by Django 4.2 on 2024-03-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0009_about_cerficate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='protfolio/static/footer_profile'),
        ),
    ]
