# Generated by Django 4.2 on 2024-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0011_alter_about_image_alter_cerficate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='footer_profile/'),
        ),
    ]
