# Generated by Django 4.2 on 2024-03-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0012_alter_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='image1',
            field=models.ImageField(null=True, upload_to='footer_profile/'),
        ),
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(null=True, upload_to='footer_profile/'),
        ),
        migrations.AddField(
            model_name='about',
            name='image3',
            field=models.ImageField(null=True, upload_to='footer_profile/'),
        ),
    ]
