# Generated by Django 4.2 on 2024-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0013_remove_about_image_about_image1_about_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='cerficate',
            name='image',
        ),
        migrations.AddField(
            model_name='cerficate',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/certificates/'),
        ),
        migrations.AddField(
            model_name='cerficate',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/certificates/'),
        ),
        migrations.AddField(
            model_name='cerficate',
            name='image3',
            field=models.ImageField(null=True, upload_to='media/certificates/'),
        ),
    ]
