# Generated by Django 4.2 on 2024-03-28 19:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0014_rename_image1_about_image_remove_about_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=300000)),
                ('demo_link', models.URLField()),
                ('video_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='video_link',
        ),
    ]
