# Generated by Django 4.2 on 2024-03-28 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0015_nodeproject_remove_project_demo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_peoject', to='protfolio.project'),
        ),
    ]
