# Generated by Django 4.2 on 2024-03-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0016_nodeproject_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_project', to='protfolio.project'),
        ),
    ]
