# Generated by Django 4.2 on 2024-03-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0017_alter_nodeproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeproject',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
