# Generated by Django 4.2 on 2024-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0020_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='leetcode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='twitter',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='website',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
