# Generated by Django 4.2 on 2024-04-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0021_resume_github_resume_leetcode_resume_twitter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='website',
            new_name='linkedIn',
        ),
    ]
