# Generated by Django 4.2 on 2024-04-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0022_rename_website_resume_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, null=True)),
                ('desct', models.CharField(max_length=400, null=True)),
                ('key_skills', models.CharField(max_length=400, null=True)),
                ('repository', models.CharField(max_length=400, null=True)),
                ('date', models.CharField(max_length=400, null=True)),
                ('author', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, null=True)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=400, null=True)),
                ('specialization', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=300, null=True)),
                ('issue_date', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=400)),
                ('branch', models.CharField(max_length=300)),
                ('marks', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('subtitle', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=400)),
                ('company', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200, null=True)),
                ('developement', models.CharField(max_length=200, null=True)),
                ('mobile_developement', models.CharField(max_length=400, null=True)),
                ('testing', models.CharField(max_length=400, null=True)),
                ('designing', models.CharField(max_length=400, null=True)),
                ('tools', models.CharField(max_length=400, null=True)),
                ('video_editing', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
