# Generated by Django 4.2 on 2024-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0023_academicproject_achievement_certificate_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notes')),
                ('title', models.CharField(max_length=300, null=True)),
                ('content', models.TextField()),
                ('pdf', models.FileField(upload_to='notes_pdf')),
            ],
        ),
    ]
